server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pets_db
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
Api:
  url: https://http.dog

logging:
  level:
    org.springframework.security: DEBUG

token:
  converter:
    principal-attribute: preferred_username
    resource-id: dog-backend
